branch-defaults:
  master:
    environment: comunidades-unidas-prod-vpc
    group_suffix: null
environment-defaults:
  comunidades-unidas-internal-prod:
    branch: null
    repository: null
global:
  application_name: comunidades-unidas-internal
  branch: null
  default_ec2_keyname: cukey-new
  default_platform: Node.js 12
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
